export const tileVariables = [
    {type: "empty", elevation: 0, color: ""},
    {type: "chest", elevation: 0, level: 1, color: "yellow"},
    {type: "wall", elevation: 10, color: ""},
    {type: "exit", elevation: 0, color: ""},
    {type: "monster", elevation: 0, level: 1, color: ""},
    {type: "empty", pushable: true, elevation: 0, color: ""},
    {type: "cliff", pushable: true, elevation: 3, color: ""},
    {type: "water", elevation: 0, color: ""},
    {type: "quicksand", elevation: 0, color: ""},
    {type: "lava", elevation: 0, color: ""},
    {type: "uneven", elevation: 0, color: ""},
    {type: "empty", mist: true, elevation: 0, color: ""},
    {type: "empty", hidden: true, elevation: 0, color: ""},
    {type: "monster", mist: true, elevation: 0, color: ""},
    {type: "chest", mist: true, elevation: 0, color: ""},
    {type: "chest", hidden: true, elevation: 0, color: ""},
    {type: "cliff", elevation: 3, color: ""},
    {type: "platform", elevation: 2, color: ""},
    {type: "platform", pushable: true, elevation: 2, color: ""},
    {type: "gold-pile", elevation: 0, level: 1, color: ""},
    {type: "empty", hidden: true, pushable: true, elevation: 0, color: ""},
    {type: "chest", elevation: 0, level: 0, color: ""},
     {type: "chest", elevation: 0, level: 1, color: ""},
    {type: "chest", elevation: 0, level: 2, color: ""},
    {type: "chest", elevation: 0, level: 3, color: ""},
    {type: "chest", elevation: 0, level: 4, color: ""},
    {type: "chest", elevation: 0, level: 5, color: ""},
     {type: "chest", elevation: 1, level: 1, color: ""},
    {type: "chest", elevation: 1, level: 2, color: ""},
    {type: "chest", elevation: 1, level: 3, color: ""},
    {type: "chest", elevation: 1, level: 4, color: ""},
    {type: "chest", elevation: 1, level: 5, color: ""},
    {type: "chest", elevation: 3, level: 1, color: ""},
    {type: "chest", elevation: 3, level: 2, color: ""},
    {type: "chest", elevation: 3, level: 3, color: ""},
    {type: "chest", elevation: 3, level: 4, color: ""},
    {type: "chest", elevation: 3, level: 5, color: ""},
    {type: "locked-door", elevation: 0, key: "k1", color: ""},
    {type: "locked-door", elevation: 1, key: "k1", color: ""},
    {type: "locked-door", elevation: 2, key: "k1", color: ""},
    {type: "unlocked-door", elevation: 1, key: "k1", color: ""},
    {type: "unlocked-door", elevation: 2, key: "k1", color: ""},
    {type: "unlocked-door", elevation: 3, key: "k1", color: ""},
    {type: "empty", elevation: 0, level: 1, itemObject: "door-key", name: "Bronze Key", code: "k1", color: ""},
    {type: "platform", elevation: 1, level: 1, itemObject: "door-key", door: [], color: ""},
    {type: "cliff", elevation: 3, level: 1, itemObject: "door-key", door: [], color: ""},
    {type: "teleporter-1", end: [11, 30], elevation: 0, color: ""},
    {type: "teleporter-1", end: [17, 33], elevation: 0, color: ""},
    {type: "teleporter-1", end: [39, 12], elevation: 0, color: ""},
    {type: "teleporter-4", end: [15, 42], elevation: 0, color: ""},
    {type: "teleporter-5", end: [15, 42], elevation: 0, color: ""},
    {type: "monster", elevation: 0, level: 1, color: ""},
    {type: "monster", elevation: 0, level: 2, color: ""},
    {type: "monster", elevation: 0, level: 3, color: ""},
    {type: "monster", elevation: 0, level: 4, color: ""},
    {type: "monster", elevation: 0, level: 5, color: ""},

     {type: "monster", elevation: 1, level: 1, color: ""},
    {type: "monster", elevation: 1, level: 2, color: ""},
    {type: "monster", elevation: 1, level: 3, color: ""},
    {type: "monster", elevation: 1, level: 4, color: ""},
    {type: "monster", elevation: 1, level: 5, color: ""},

    {type: "monster", elevation: 3, level: 1, color: ""},
    {type: "monster", elevation: 3, level: 2, color: ""},
    {type: "monster", elevation: 3, level: 3, color: ""},
    {type: "monster", elevation: 3, level: 4, color: ""},
    {type: "monster", elevation: 3, level: 5, color: ""},
    {type: "lookout", elevation: 0, color: ""},
    {type: "lookout", elevation: 1, color: ""},
    {type: "lookout", elevation: 3, color: ""},
    {type: "lookout-hidden-door", elevation: 0, area: [], color: ""},
    {type: "hidden-door", elevation: 0, color: ""},
]
